version: '3.1'

services:

  api:
    container_name: ${API_NAME}
    build:
        context: "."
    command: ['node', 'app.js']
    restart: always
    ports:
      - ${API_PORT}:3001
    environment:
      - DB_HOST=db
    networks:
        - network
    depends_on:
        - db

  db:
    container_name: escape_api_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

    networks:
        - network
    volumes:
      - db:/data/db
    ports:
        - ${DB_PORT}:${DB_PORT}

volumes:
  db:

networks:
    network:
        name: "net"